import type { State } from "./types.ts";
import { PCode } from "../constants/pcodes.ts";
import * as actions from "./actions.ts";

type Action = (state: State) => CodeResult;

type CodeResult = {
  state: State;
  drawn: boolean;
  halted: boolean;
}

export default {
  // 0x00s - basic stack operations, conversion operators
  [PCode.null]: actions.doNothing,
  [PCode.dupl]: actions.doNothing,
  [PCode.swap]: actions.doNothing,
  [PCode.rota]: actions.doNothing,
  [PCode.incr]: actions.doNothing,
  [PCode.decr]: actions.doNothing,
  [PCode.mxin]: actions.doNothing,
  [PCode.rand]: actions.doNothing,
  [PCode.hstr]: actions.doNothing,
  [PCode.ctos]: actions.doNothing,
  [PCode.sasc]: actions.doNothing,
  [PCode.itos]: actions.doNothing,
  [PCode.hexs]: actions.doNothing,
  [PCode.sval]: actions.doNothing,
  [PCode.qtos]: actions.doNothing,
  [PCode.qval]: actions.doNothing,
  // 0x10s - Boolean operators, integer operators
  [PCode.not]: actions.doNothing,
  [PCode.and]: actions.doNothing,
  [PCode.or]: actions.doNothing,
  [PCode.xor]: actions.doNothing,
  [PCode.andl]: actions.doNothing,
  [PCode.orl]: actions.doNothing,
  [PCode.shft]: actions.doNothing,
  [PCode.neg]: actions.doNothing,
  [PCode.abs]: actions.doNothing,
  [PCode.sign]: actions.doNothing,
  [PCode.plus]: actions.doNothing,
  [PCode.subt]: actions.doNothing,
  [PCode.mult]: actions.doNothing,
  [PCode.divr]: actions.doNothing,
  [PCode.div]: actions.doNothing,
  [PCode.mod]: actions.doNothing,
  // 0x20s - comparison operators
  [PCode.eqal]: actions.doNothing,
  [PCode.noeq]: actions.doNothing,
  [PCode.less]: actions.doNothing,
  [PCode.more]: actions.doNothing,
  [PCode.lseq]: actions.doNothing,
  [PCode.mreq]: actions.doNothing,
  [PCode.maxi]: actions.doNothing,
  [PCode.mini]: actions.doNothing,
  [PCode.seql]: actions.doNothing,
  [PCode.sneq]: actions.doNothing,
  [PCode.sles]: actions.doNothing,
  [PCode.smor]: actions.doNothing,
  [PCode.sleq]: actions.doNothing,
  [PCode.smeq]: actions.doNothing,
  [PCode.smax]: actions.doNothing,
  [PCode.smin]: actions.doNothing,
  // 0x30s - pseudo-real operators
  [PCode.divm]: actions.doNothing,
  [PCode.sqrt]: actions.doNothing,
  [PCode.hyp]: actions.doNothing,
  [PCode.root]: actions.doNothing,
  [PCode.powr]: actions.doNothing,
  [PCode.log]: actions.doNothing,
  [PCode.alog]: actions.doNothing,
  [PCode.ln]: actions.doNothing,
  [PCode.exp]: actions.doNothing,
  [PCode.sin]: actions.doNothing,
  [PCode.cos]: actions.doNothing,
  [PCode.tan]: actions.doNothing,
  [PCode.asin]: actions.doNothing,
  [PCode.acos]: actions.doNothing,
  [PCode.atan]: actions.doNothing,
  [PCode.pi]: actions.doNothing,
  // 0x40s - string operators
  [PCode.scat]: actions.doNothing,
  [PCode.slen]: actions.doNothing,
  [PCode.case]: actions.doNothing,
  [PCode.copy]: actions.doNothing,
  [PCode.dels]: actions.doNothing,
  [PCode.inss]: actions.doNothing,
  [PCode.poss]: actions.doNothing,
  [PCode.repl]: actions.doNothing,
  [PCode.spad]: actions.doNothing,
  [PCode.trim]: actions.doNothing,
  // 0x50s - turtle settings and movement
  [PCode.home]: actions.doNothing,
  [PCode.setx]: actions.doNothing,
  [PCode.sety]: actions.doNothing,
  [PCode.setd]: actions.doNothing,
  [PCode.angl]: actions.doNothing,
  [PCode.thik]: actions.doNothing,
  [PCode.pen]: actions.doNothing,
  [PCode.colr]: actions.doNothing,
  [PCode.toxy]: actions.doNothing,
  [PCode.mvxy]: actions.doNothing,
  [PCode.drxy]: actions.doNothing,
  [PCode.fwrd]: actions.doNothing,
  [PCode.back]: actions.doNothing,
  [PCode.left]: actions.doNothing,
  [PCode.rght]: actions.doNothing,
  [PCode.turn]: actions.doNothing,
  // 0x60s - colour operators, shapes and fills
  [PCode.blnk]: actions.doNothing,
  [PCode.rcol]: actions.doNothing,
  [PCode.fill]: actions.doNothing,
  [PCode.pixc]: actions.doNothing,
  [PCode.pixs]: actions.doNothing,
  [PCode.rgb]: actions.doNothing,
  [PCode.mixc]: actions.doNothing,
  [PCode.rmbr]: actions.doNothing,
  [PCode.frgt]: actions.doNothing,
  [PCode.poly]: actions.doNothing,
  [PCode.pfil]: actions.doNothing,
  [PCode.circ]: actions.doNothing,
  [PCode.blot]: actions.doNothing,
  [PCode.elps]: actions.doNothing,
  [PCode.eblt]: actions.doNothing,
  [PCode.box]: actions.doNothing,
  // 0x70s - loading from stack, storing from stack, pointer and array operations
  [PCode.ldin]: actions.doNothing,
  [PCode.ldvg]: actions.doNothing,
  [PCode.ldvv]: actions.doNothing,
  [PCode.ldvr]: actions.doNothing,
  [PCode.ldag]: actions.doNothing,
  [PCode.ldav]: actions.doNothing,
  [PCode.lstr]: actions.doNothing,
  [PCode.stvg]: actions.doNothing,
  [PCode.stvv]: actions.doNothing,
  [PCode.stvr]: actions.doNothing,
  [PCode.lptr]: actions.doNothing,
  [PCode.sptr]: actions.doNothing,
  [PCode.zptr]: actions.doNothing,
  [PCode.cptr]: actions.doNothing,
  [PCode.cstr]: actions.doNothing,
  [PCode.test]: actions.doNothing,
  // 0x80s - flow control, memory control
  [PCode.jump]: actions.doNothing,
  [PCode.ifno]: actions.doNothing,
  [PCode.halt]: actions.doNothing,
  [PCode.subr]: actions.doNothing,
  [PCode.retn]: actions.doNothing,
  [PCode.pssr]: actions.doNothing,
  [PCode.plsr]: actions.doNothing,
  [PCode.psrj]: actions.doNothing,
  [PCode.plrj]: actions.doNothing,
  [PCode.ldmt]: actions.doNothing,
  [PCode.stmt]: actions.doNothing,
  [PCode.memc]: actions.doNothing,
  [PCode.memr]: actions.doNothing,
  [PCode.hfix]: actions.doNothing,
  [PCode.hclr]: actions.doNothing,
  [PCode.hrst]: actions.doNothing,
  // 0x90s - runtime variables, debugging
  [PCode.canv]: actions.doNothing,
  [PCode.reso]: actions.doNothing,
  [PCode.udat]: actions.doNothing,
  [PCode.seed]: actions.doNothing,
  [PCode.trac]: actions.doNothing,
  [PCode.memw]: actions.doNothing,
  [PCode.dump]: actions.doNothing,
  [PCode.peek]: actions.doNothing,
  [PCode.poke]: actions.doNothing,
  // 0xa0s - text output, timing
  [PCode.stat]: actions.doNothing,
  [PCode.iclr]: actions.doNothing,
  [PCode.bufr]: actions.doNothing,
  [PCode.read]: actions.doNothing,
  [PCode.rdln]: actions.doNothing,
  [PCode.kech]: actions.doNothing,
  [PCode.outp]: actions.doNothing,
  [PCode.cons]: actions.doNothing,
  [PCode.prnt]: actions.doNothing,
  [PCode.writ]: actions.doNothing,
  [PCode.newl]: actions.doNothing,
  [PCode.curs]: actions.doNothing,
  [PCode.time]: actions.doNothing,
  [PCode.tset]: actions.doNothing,
  [PCode.wait]: actions.doNothing,
  [PCode.tdet]: actions.doNothing,
  // 0xb0s - file processing
  [PCode.chdr]: actions.doNothing,
  [PCode.file]: actions.doNothing,
  [PCode.diry]: actions.doNothing,
  [PCode.open]: actions.doNothing,
  [PCode.clos]: actions.doNothing,
  [PCode.fbeg]: actions.doNothing,
  [PCode.eof]: actions.doNothing,
  [PCode.eoln]: actions.doNothing,
  [PCode.frds]: actions.doNothing,
  [PCode.frln]: actions.doNothing,
  [PCode.fwrs]: actions.doNothing,
  [PCode.fwln]: actions.doNothing,
  [PCode.ffnd]: actions.doNothing,
  [PCode.fdir]: actions.doNothing,
  [PCode.fnxt]: actions.doNothing,
  [PCode.fmov]: actions.doNothing,
  // 0xe0s - dummy codes
  [PCode.dopr]: actions.doNothing,
  [PCode.fopr]: actions.doNothing,
  [PCode.ilin]: actions.doNothing,
  [PCode.lefs]: actions.doNothing,
  [PCode.newt]: actions.doNothing,
  [PCode.oldt]: actions.doNothing,
  [PCode.rgts]: actions.doNothing,
  [PCode.rndc]: actions.doNothing,
  [PCode.svd0]: actions.doNothing,
  [PCode.wrln]: actions.doNothing,
} satisfies Record<PCode, Action>;
